name: Backend

defaults:
  run:
    working-directory: backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build:
    name: Build
    environment: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: frontend
      - name: yarn install
        run: yarn
      - name: build
        run: yarn build
