name: Frontend

defaults:
  run:
    working-directory: frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-ios:
    name: Build iOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: frontend
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: install
        run: yarn install
      - name: build ios
        run: expo build:ios
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: frontend
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: install
        run: yarn install
      - name: build ios
        run: expo build:android
  # test:
  #   name: Test
  #   environment: Test
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     # - run: cd client && npm install -g yarn
  #     - name: yarn install and test
  #       run: |
  #         cd client
  #         yarn
  #         yarn test
