name: Frontend

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  build-ios:
    name: Build
    environment: Test
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: cd client && npm install -g yarn
      - name: yarn install and build
        run: |
          cd frontend
          yarn 
          yarn build:ios
  build-android:
    name: Build
    environment: Test
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: cd client && npm install -g yarn
      - name: yarn install and build
        run: |
          cd frontend
          yarn 
          yarn build:android
  # test:
  #   name: Test
  #   environment: Test
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     # - run: cd client && npm install -g yarn
  #     - name: yarn install and test
  #       run: |
  #         cd client
  #         yarn
  #         yarn test
